"""init

Revision ID: 120b77d95bde
Revises: 24993e230206
Create Date: 2018-08-21 16:12:12.719622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120b77d95bde'
down_revision = '24993e230206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
