"""init

Revision ID: 24993e230206
Revises: 
Create Date: 2018-08-20 17:54:35.986112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24993e230206'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcase',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('SPLEase', sa.String(length=255), nullable=True),
    sa.Column('alertvolume', sa.String(length=255), nullable=True),
    sa.Column('app', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('dashboard', sa.String(length=255), nullable=True),
    sa.Column('datasource', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('displayapp', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('examples_label', sa.Text(), nullable=True),
    sa.Column('examples_name', sa.String(length=255), nullable=True),
    sa.Column('gdpr', sa.String(length=255), nullable=True),
    sa.Column('gdprtext', sa.Text(), nullable=True),
    sa.Column('hasSearch', sa.String(length=255), nullable=True),
    sa.Column('help', sa.Text(), nullable=True),
    sa.Column('highlight', sa.String(length=255), nullable=True),
    sa.Column('howToImplement', sa.Text(), nullable=True),
    sa.Column('ids_type', sa.String(length=255), nullable=True),
    sa.Column('images_label', sa.Text(), nullable=True),
    sa.Column('images_name', sa.String(length=255), nullable=True),
    sa.Column('images_path', sa.String(length=255), nullable=True),
    sa.Column('journey', sa.Text(), nullable=True),
    sa.Column('killchain', sa.Text(), nullable=True),
    sa.Column('knownFP', sa.Text(), nullable=True),
    sa.Column('mitre', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_label', sa.Text(), nullable=True),
    sa.Column('operationalize', sa.Text(), nullable=True),
    sa.Column('released', sa.String(length=255), nullable=True),
    sa.Column('relevance', sa.Text(), nullable=True),
    sa.Column('similarUseCases', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('usecase', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('showcasedemo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actions_UBASeverity', sa.Integer(), nullable=True),
    sa.Column('cardinalityTest', sa.Text(), nullable=True),
    sa.Column('change_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('examples_name', sa.String(length=255), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('outlierPeerGroup', sa.String(length=255), nullable=True),
    sa.Column('outlierValueTracked1', sa.Text(), nullable=True),
    sa.Column('outlierValueTracked2', sa.Text(), nullable=True),
    sa.Column('outlierVariable', sa.String(length=255), nullable=True),
    sa.Column('outlierVariableSubject', sa.String(length=255), nullable=True),
    sa.Column('prereqs_field', sa.Text(), nullable=True),
    sa.Column('prereqs_greaterorequalto', sa.Text(), nullable=True),
    sa.Column('prereqs_name', sa.String(length=255), nullable=True),
    sa.Column('prereqs_override_auto_finalize', sa.Text(), nullable=True),
    sa.Column('prereqs_resolution', sa.Text(), nullable=True),
    sa.Column('prereqs_test', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examples_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showcasedemo')
    op.drop_table('showcase')
    # ### end Alembic commands ###
