"""add_cn

Revision ID: 2e89c22f6131
Revises: 4b7c7220c4a0
Create Date: 2018-09-07 11:21:40.995253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e89c22f6131'
down_revision = '4b7c7220c4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcasecn',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('SPLEase', sa.String(length=255), nullable=True),
    sa.Column('alertvolume', sa.String(length=255), nullable=True),
    sa.Column('app', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('dashboard', sa.String(length=255), nullable=True),
    sa.Column('datasource', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('displayapp', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('examples_label', sa.Text(), nullable=True),
    sa.Column('examples_name', sa.String(length=255), nullable=True),
    sa.Column('gdpr', sa.String(length=255), nullable=True),
    sa.Column('gdprtext', sa.Text(), nullable=True),
    sa.Column('hasSearch', sa.String(length=255), nullable=True),
    sa.Column('help', sa.Text(), nullable=True),
    sa.Column('highlight', sa.String(length=255), nullable=True),
    sa.Column('howToImplement', sa.Text(), nullable=True),
    sa.Column('ids_type', sa.String(length=255), nullable=True),
    sa.Column('images_label', sa.Text(), nullable=True),
    sa.Column('images_name', sa.String(length=255), nullable=True),
    sa.Column('images_path', sa.String(length=255), nullable=True),
    sa.Column('journey', sa.Text(), nullable=True),
    sa.Column('killchain', sa.Text(), nullable=True),
    sa.Column('knownFP', sa.Text(), nullable=True),
    sa.Column('mitre', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_label', sa.Text(), nullable=True),
    sa.Column('operationalize', sa.Text(), nullable=True),
    sa.Column('released', sa.String(length=255), nullable=True),
    sa.Column('relevance', sa.Text(), nullable=True),
    sa.Column('similarUseCases', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('usecase', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('showcaseen',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('SPLEase', sa.String(length=255), nullable=True),
    sa.Column('alertvolume', sa.String(length=255), nullable=True),
    sa.Column('app', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('dashboard', sa.String(length=255), nullable=True),
    sa.Column('datasource', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('displayapp', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('examples_label', sa.Text(), nullable=True),
    sa.Column('examples_name', sa.String(length=255), nullable=True),
    sa.Column('gdpr', sa.String(length=255), nullable=True),
    sa.Column('gdprtext', sa.Text(), nullable=True),
    sa.Column('hasSearch', sa.String(length=255), nullable=True),
    sa.Column('help', sa.Text(), nullable=True),
    sa.Column('highlight', sa.String(length=255), nullable=True),
    sa.Column('howToImplement', sa.Text(), nullable=True),
    sa.Column('ids_type', sa.String(length=255), nullable=True),
    sa.Column('images_label', sa.Text(), nullable=True),
    sa.Column('images_name', sa.String(length=255), nullable=True),
    sa.Column('images_path', sa.String(length=255), nullable=True),
    sa.Column('journey', sa.Text(), nullable=True),
    sa.Column('killchain', sa.Text(), nullable=True),
    sa.Column('knownFP', sa.Text(), nullable=True),
    sa.Column('mitre', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_label', sa.Text(), nullable=True),
    sa.Column('operationalize', sa.Text(), nullable=True),
    sa.Column('released', sa.String(length=255), nullable=True),
    sa.Column('relevance', sa.Text(), nullable=True),
    sa.Column('similarUseCases', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('usecase', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index('name', table_name='showcase')
    op.drop_table('showcase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcase',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('SPLEase', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('alertvolume', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dashboard', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('datasource', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('displayapp', mysql.TEXT(), nullable=True),
    sa.Column('domain', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('examples_label', mysql.TEXT(), nullable=True),
    sa.Column('examples_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gdpr', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gdprtext', mysql.TEXT(), nullable=True),
    sa.Column('hasSearch', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('help', mysql.TEXT(), nullable=True),
    sa.Column('highlight', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('howToImplement', mysql.TEXT(), nullable=True),
    sa.Column('ids_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('images_label', mysql.TEXT(), nullable=True),
    sa.Column('images_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('images_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('journey', mysql.TEXT(), nullable=True),
    sa.Column('killchain', mysql.TEXT(), nullable=True),
    sa.Column('knownFP', mysql.TEXT(), nullable=True),
    sa.Column('mitre', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name_label', mysql.TEXT(), nullable=True),
    sa.Column('operationalize', mysql.TEXT(), nullable=True),
    sa.Column('released', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('relevance', mysql.TEXT(), nullable=True),
    sa.Column('similarUseCases', mysql.TEXT(), nullable=True),
    sa.Column('story', mysql.TEXT(), nullable=True),
    sa.Column('usecase', mysql.TEXT(), nullable=True),
    sa.Column('developer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_index('name', 'showcase', ['name'], unique=True)
    op.drop_table('showcaseen')
    op.drop_table('showcasecn')
    # ### end Alembic commands ###
