"""add user

Revision ID: 4b7c7220c4a0
Revises: 873e374534ca
Create Date: 2018-08-29 17:54:15.818417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7c7220c4a0'
down_revision = '873e374534ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=True),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('expire_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.add_column(u'showcase', sa.Column('developer', sa.String(length=255), nullable=True))
    op.add_column(u'showcase', sa.Column('owner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'showcase', 'owner')
    op.drop_column(u'showcase', 'developer')
    op.drop_table('user_token')
    op.drop_table('user')
    # ### end Alembic commands ###
