"""init

Revision ID: 7b38bf7d3a1a
Revises: 120b77d95bde
Create Date: 2018-08-21 17:21:27.658651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b38bf7d3a1a'
down_revision = '120b77d95bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
