"""add owner and developer

Revision ID: 873e374534ca
Revises: 7b38bf7d3a1a
Create Date: 2018-08-29 17:26:55.396429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873e374534ca'
down_revision = '7b38bf7d3a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
